package auth

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/repooooo/graphqls/go/gen/auth"
	"github.com/repooooo/graphqls/go/gen/auth/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginRequest) (*model.LoginResponse, error) {
	return r.Login(ctx, input)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input model.LogoutRequest) (*model.LogoutResponse, error) {
	return r.Logout(ctx, input)
}

// Mutation returns auth.MutationResolver implementation.
func (r *Resolver) Mutation() auth.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
